server:
  port: 8080

spring:
  application:
    name: SpringSecurityTemplate

  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: sjyoon
    password: yoon!123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.dev.security.domain

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

# 보안 설정
security:
  basic:
    enabled: false